from enum import Enum

class TokenType(Enum):
    IDENTIFIER = "IDENTIFIER"
    NUMBER = "NUMBER"
    REL_OPERATOR = "REL_OPERATOR"
    MATH_OPERATOR = "MATH_OPERATOR"
    ASSIGNMENT = "ASSIGNMENT"
    LPAREN = "LPAREN"
    RPAREN = "RPAREN"
    COLON = "COLON"
    STRING = "STRING"
    SEMICOLON = "SEMICOLON"
    LBRACE = "LBRACE"
    RBRACE = "RBRACE"
    LOG_OPERATOR = "LOG_OPERATOR"

    # Palavras reservadas
    DECLARACOES = "DECLARACOES"
    ALGORITMO = "ALGORITMO"
    INTEIRO = "INTEIRO"
    REAL = "REAL"
    LER = "LER"
    IMPRIMIR = "IMPRIMIR"
    SE = "SE"
    ENTAO = "ENTAO"
    SENAO = "SENAO"
    ENQUANTO = "ENQUANTO"
    INICIO = "INICIO"
    FIM = "FIM"
    E = "E"
    OU = "OU"

    EOF = "EOF"